### ISSUE TITLE
AttributeError: 'ConstrainedLinearRegression' object has no attribute '_preprocess_data'

### ISSUE THREAD

**Issue by yibe-good** [avidale/constrained-linear-regression#1]
Thank you for the nice project.
I just installed constrained-linear-regression on my computer through "pip install constrained-linear-regression".
However, I failed to run the example codes. It always shows 'ConstrainedLinearRegression' object has no attribute '_preprocess_data'.
I installed python through Anaconda, and I used pycharm to run the code.

sklearn/Python version information:
1.1.1/ 3.9.12

**Comment by voskresenskiianton** [comment]
I got the same issue

**Comment by avidale** [comment]
Sorry for not responding for a long time. 
As a quick remedy, please try downgrading scikit-learn to 1.0. 
Meanwhile, I'll update my library.

**Comment by avidale** [comment]
Fixed the problem in v0.0.4 (https://pypi.org/project/constrained-linear-regression/0.0.4/), please try @voskresenskiianton @yibe-good

**Comment by voskresenskiianton** [comment]
@avidale works just fine! thanks a lot!
